# Generated by Django 2.2.13 on 2020-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_own',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
    ]
