# Generated by Django 2.2.13 on 2020-07-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='team_id',
            field=models.TextField(default='team1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='team_id',
            field=models.TextField(default='team1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_own',
            name='team_id',
            field=models.TextField(default='team1'),
            preserve_default=False,
        ),
    ]
